services:
  - type: web
    name: vehicle-dashboard
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "./start.sh"
    runtime: "python"
    pythonVersion: "3.11"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PORT
        value: "8501"
