# Streamlit Cloud Secrets
# Add your API keys and sensitive information here
# Reference in your code with st.secrets["VAHAN_API_KEY"]

VAHAN_API_KEY = "your_api_key_here"
DB_URI = "sqlite:///data/vehicle_data.db"
